### ISSUE TITLE
Identical names

### ISSUE THREAD

**Issue by larsga** [atlefren/norske_prestegjeld#1]
Very useful data! But having three prestegjeld all named "Næss" is a bit awkward. I want to make choropleth map, and I can't write matching rules that distinguish between these.

Would it be possible to do something like:

```
"properties": { 
  "name": "Næss",
  "unique_name": "Næss 1"  
}
```

That way, there would be a unique name to match on where needed.

**Comment by atlefren** [comment]
I see the problem, but I would suggest the following approach

1. Use the "id" param in the GeoJson spec. 
2. Use a guid for the ID, as having "Næss 1" and "Næss 2" kinda implies some ordering.

**Comment by larsga** [comment]
That makes sense, but guids are long and awkward. Perhaps just generate random identifiers of three lowercase letters instead? I can make the code ensure they are unique.

**Comment by atlefren** [comment]
Yeah, guids are kinda overkill, agreed. Your suggestion makes perfect sense! 

-- 
  Atle Frenvik Sveen
  ***@***.***
  45278689
  atlefren.net
