### ISSUE TITLE
Clipped geography

### ISSUE THREAD

**Issue by larsga** [atlefren/norske_prestegjeld#2]
In the current JSON file the boundaries go far out to sea, which is fine for some applications. I want to make choropleths, so for me it doesn't work. I made a version clipped to the borders of Norway (as of 2015, though). I'd be happy to upload that if it's useful.

**Comment by atlefren** [comment]
Yeah, this is a known problem, since I have based the data on the municipal borders from kartverket.

Adding the clipped versions is most definately welcome. I would suggest we add unique identifiers to each feature first, though?

**Comment by larsga** [comment]
Guess we can close this now?

**Comment by atlefren** [comment]
absolutely!
